SELECT ID, 
CASE 
    WHEN COLONY_RANK = 1 THEN 'CRITICAL'
    WHEN COLONY_RANK = 2 THEN 'HIGH'
    WHEN COLONY_RANK = 3 THEN 'MEDIUM'
    ELSE 'LOW'
END COLONY_NAME
FROM (SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) COLONY_RANK 
      FROM ECOLI_DATA
     ) SUB_QUERY     
ORDER BY ID