/*
2022년 1월 구매 user id 1 gender = 1, 4 gender =4
2022년 2월 구매 user id 2 g=null, 5 g=1, 6 g=1
*/

SELECT 
YEAR(SALES_DATE) AS YEAR,  
MONTH(SALES_DATE) AS MONTH, 
A.GENDER, 
COUNT(DISTINCT B.USER_ID) AS USERS
FROM USER_INFO A
JOIN ONLINE_SALE B ON B.USER_ID = A.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER