SELECT EM.EMP_NO, EM.EMP_NAME, 
CASE 
WHEN AVG(G.SCORE) >= 96 THEN "S" 
WHEN AVG(G.SCORE) >= 90 THEN "A"
WHEN AVG(G.SCORE) >= 80 THEN "B"
ELSE "C"
END AS GRADE, 
CASE
WHEN AVG(G.SCORE) >= 96 THEN 0.2 * EM.SAL
WHEN AVG(G.SCORE) >= 90 THEN 0.15 * EM.SAL
WHEN AVG(G.SCORE) >= 80 THEN 0.1 * EM.SAL
ELSE 0 * EM.SAL
END AS BONUS
FROM HR_DEPARTMENT D
JOIN HR_EMPLOYEES EM ON D.DEPT_ID = EM.DEPT_ID
JOIN HR_GRADE G ON EM.EMP_NO = G.EMP_NO
GROUP BY EM.EMP_NO
ORDER BY EM.EMP_NO